version: '3'
services:

  web-app-flask:
    build: .
    container_name: web-app-flask
    command: sh -c py app.py
    ports:
      - "5000:5000"
    depends_on:
      - "db-redis-test"

  db-redis-test:
    image: redis:latest
    container_name: redis
    ports:
      - "6376:6379"
    networks:
      - nsql-net